"""init_project(1)

Revision ID: 249975567242
Revises: d1d544b905fe
Create Date: 2026-05-15 16:52:28.019117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249975567242'
down_revision = 'd1d544b905fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
