"""fix_donation_comment_default_none

Revision ID: 545fafea7f4a
Revises: 249975567242
Create Date: 2026-05-15 17:28:30.759367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545fafea7f4a'
down_revision = '249975567242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
